#include "osci_licensing.h"

#include "third_party/monocypher/monocypher.c"
#include "third_party/monocypher/monocypher-ed25519.c"

#include "license/osci_LicenseToken.cpp"
#include "network/osci_BackendClient.cpp"
#include "feedback/osci_FeedbackClient.cpp"
#include "feedback/osci_FeedbackContextBuilder.cpp"
#include "feedback/osci_FeedbackSettingsOverlay.cpp"
#include "feedback/osci_FeedbackSuccessOverlay.cpp"
#include "feedback/osci_FeedbackOverlay.cpp"
#include "state/osci_UpdateSettings.cpp"
#include "license/osci_LicenseManager.cpp"
#include "system/osci_HardwareInfo.cpp"
#include "system/osci_DawProcessDetector.cpp"
#include "update/osci_UpdateChecker.cpp"
#include "update/osci_Downloader.cpp"
#include "update/osci_PendingInstall.cpp"
#include "update/osci_InstallerLauncher.cpp"
#include "update/osci_LinuxInstallSettings.cpp"
#include "update/osci_LinuxInstaller.cpp"
